### ISSUE TITLE
switch from curl_escape() to curl_easy_escape()

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdbq#119]
curl_escape(3) man page says "Since 7.15.4, curl_easy_escape(3) should be used. This function will be removed in a future  release."
Only complication to switching functions is the need to do `CURL *curl = curl_easy_init();`
and then free that (which is not shown in the curl_easy_escape man page).

**Comment by vixie** [comment]
ok by me. send PR?

**Comment by djw1149** [comment]
done  - https://github.com/dnsdb/dnsdbq/pull/120
