### ISSUE TITLE
add to man page about running own copy of the Routeviews zone

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdbq#162]
For the asnlookup branch, add to man page about running own copy of the Routeviews zone.
The data is available from http://archive.routeviews.org/dnszones/
The Routeviews data is licensed "Creative Commons v4 w/ Attribution
license visible at  https://creativecommons.org/licenses/by/4.0/."
per http://www.routeviews.org/routeviews/index.php/faq/

We could also talk about stealth secondary zones and why one needs to run their own RDNS to get better privacy and
better performance.

**Comment by vixie** [comment]
the ASINFO LOOKUPS section of the man page intends to cover this topic. please identify any specific gaps.

`ASINFO LOOKUPS
     When the -a option is used, every address seen in a response will cause a
     DNS lookup under the domain specified by the -D option. This stream of
     DNS queries might be an intolerable information leak depending on the
     nature of the underlying research, and it could also lead to unusably bad
     performance depending on the placement of your configured recursive DNS
     service.

     For best results, always use an on-server or on-LAN recursive DNS ser-
     vice, and consider whether to configure that recursive DNS service to be
     a "stealth secondary" of the zone denoted by the -D option. For the
     default -D value, more information can be found online at
     http://archive.routeviews.org/dnszones/.

     Use of DNS lookups to retrieve ASINFO metadata can be extremely fast and
     surveillance-free, but some attention must be paid in order to obtain
     that outcome. For occasional low-volume use, your current recursive DNS
     placement and configuration is probably good enough.`

**Comment by djw1149** [comment]
That works, thanks.  I apologize for missing that change in the various commits.  Closing this.
