### ISSUE TITLE
IDN awareness

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdbq#174]
Normally dnsdbq requires that -n or -r arguments are 7-bit ASCII clean.  Non-ASCII values should be queried using PUNYCODE IDN encoding.  The -8 option allows using arbitrary 8 bit values.

We would like to support IDNs on both input and output.  This would allow specifying arbitrary 8 bit values (i.e. native character encodings) as command-line arguments or in batch files and outputting either the PUNYCODE or native character encodings.

**Comment by djw1149** [comment]
Paul: you changed some relevant code in the multitype branch, maybe you want this issue?

**Comment by vixie** [comment]
i think IDN support would be beneficial, but i loathe adding more dependencies beyond libcurl and libjansson. i think this issue should remain open until that day, someday, when dnsdbq is put under autoconf/automake.

**Comment by vixie** [comment]
time expired.
