### ISSUE TITLE
man page edits

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdbq#18]
1. Add an example to the FILES section.  It doesn't say if you need "APIKEY abcdef.." or "APIKEY=abcdef...".
  2. It doesn't say if comments are allowed.  
  3. Allowing # comments would be nice.
  4.  It doesn't document the `circla` or `circls` keyworks.  
  5. The code says the option names are actually "apikey" and "server" (lower case only), not as shown in the man page, APIKEY and DNSDB_SERVER.
  6. I think these option names should be the same as the environment variable names, DNSDB_API_KEY and DNSDB_SERVER, for consistency.
  
```
FILES
     ~/.isc-dnsdb-query.conf, ~/.dnsdb-query.conf, /etc/isc-dnsdb-query.conf, or /etc/dnsdb-query.conf: configuration file which should contain the user's apikey and server URL.

     APIKEY: contains the user's apikey (no default)
     DNSDB_SERVER: contains the URL of the DNSDB API server (default is https://api.dnsdb.info)
```

**Comment by vixie** [comment]
djw1149 wrote:
>  1. Add an example to the FILES section. It doesn't say if you need
>     "APIKEY abcdef.." or "APIKEY=abcdef...".
>  2. It doesn't say if comments are allowed.
>  3. Allowing # comments would be nice.

it should say those things. the parser is POSIX /bin/sh, so yes, 
comments are allowed. grep for "popen".

>  4. It doesn't document the |circla| or |circls| keyworks.
>  5. The code says the option names are actually "apikey" and "server"
>     (lower case only), not as shown in the man page, APIKEY and
>     DNSDB_SERVER.
>  6. I think these option names should be the same as the environment
>     variable names, DNSDB_API_KEY and DNSDB_SERVER, for consistency.

those names (circla, circls, apikey, server) are internal names, output 
by /bin/sh based on what it finds in the config file. they will never be 
seen and cannot be set by the user. grep for "echo".

-- 
P Vixie

**Comment by djw1149** [comment]
I will change the man page to show an example config file and explain that shell comments work.
