### ISSUE TITLE
Exit failure code for 404 error?  Error message understandability

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdbq#20]
When a query fails with a 404, should the exit failure code really be 0 as shown below?:
```
$ dnsdbq -r www.farsightsecurity.com/A -A 2015-08-25 -c
libcurl: 404 (https://api.dnsdb.info/lookup/rrset/name/www.farsightsecurity.com/A?time_first_after=1440478500)
please note: 404 usually just means that no records matched the search criteria
API: Error: no results found for query.
$ echo $?
0
```
Additionally, there are multiple messages in that output, libcurl's low level response, the query sent, a note about what 404 means, and then "API: Error".  Kind of confusing?  Can we make it more clear?

**Comment by vixie** [comment]
djw1149 wrote:
> When a query fails with a 404, should the exit failure code really be 0
> as shown below?:

yes. if the underlying api had a response code to differentiate between 
NXDOMAIN and NODATA, then i would want us to exit(1) on the former and 
exit(0) on the latter. there is no such underlying signal pattern, so it 
cannot be considered an error that there happen to be no answers. 
exit(1) is only used by dnsdbq to say that the user's input is insensible.

> |$ dnsdbq -r www.farsightsecurity.com/A -A 2015-08-25 -c
> libcurl: 404 (https://api.dnsdb.info/lookup/rrset/name/www.farsightsecurity.com/A?time_first_after=1440478500)
> please note: 404 usually just means that no records matched the search criteria
> API: Error: no results found for query.
> $ echo $?
> 0
> |
>
> Additionally, there are multiple messages in that output, libcurl's low
> level response, the query sent, a note about what 404 means, and then
> "API: Error". Kind of confusing? Can we make it more clear?

the libcurl error and API URL are shown in case the user wants to cut 
and paste into a "curl" command line to better understand the error.

the "please note" message is displayed by us to make sure the user knows 
that 404 in this case could just mean NODATA.

the API: Error: message is the payload that came with the 404, shown in 
case the API server eventually starts to say something more useful here.

what's your suggestion for adding clarity, given that we have to 
preserve the total content shown, in some form?

-- 
P Vixie

**Comment by djw1149** [comment]
The libcurl URL is not sufficient to cut and paste into a "curl" command line -- you need the -H flags etc.:
`$ curl -Ss -H 'X-API-Key: <<censored>>' -H 'Accept: text/plain' https://api.dnsdb.info/lookup/rate_limit`

I have to think still how to add clarity.

**Comment by vixie** [comment]
timeout.
