### ISSUE TITLE
`timeval_str` outputs the wrong subsecond component

### ISSUE THREAD

**Issue by mwaitzman** [dnsdb/dnsdbq#229]
`timeval_str`, when `milliseconds` is true, outputs the 3 digit *micro*second component instead of the *milli*second component

To fix, replace `usecs % 1000` with `usecs / 1000` in time.c:84

Also, I *think* `usecs % 1000000` can be replaced with just `usecs` in time.c:86

**Comment by djw1149** [comment]
I verified the problem exists and the proposed fixes work.

**Comment by djw1149** [comment]
Pull request is https://github.com/dnsdb/dnsdbq/pull/230
