### ISSUE TITLE
dnsdbq sometimes throws "warning: no seventh SP in" some (but not all) SOA records

### ISSUE THREAD

**Issue by stsauver** [dnsdb/dnsdbq#231]
Hi,

Thanks for all the work on dnsdbq, just love it!

While recently running dnsdbq to enrich a batch of 2nd-level effective domains, most are working exactly as expected,  but I'm seeing a few new-to-me errors:

```
$ nohup cat left-to-do.txt | dnsdbq -ffm -j -s -k first >> finding-the-rest.txt &
[1] 99235
$ nohup: ignoring input and redirecting stderr to stdout
```
[all fine so far, but then...]

```
dnsdbq [2024-11-01 10:14:43]: warning: no seventh SP in '1618298208 1618786009 487801 9 com455890 TXT  {"obj":{"count":9,"time_first":1618298208,"time_last":1618786009,"rrname":"455890.com.","rrtype":"TXT","bailiwick":"455890.com.","rdata":[""]}}
'
dnsdbq [2024-11-01 10:59:18]: warning: no seventh SP in '1415592475 1415592475 0 2 comitempf SOA  {"obj":{"count":2,"time_first":1415592475,"time_last":1415592475,"rrname":"itempf.com.","rrtype":"SOA","bailiwick":"itempf.com.","rdata":[""]}}
```
'
Note the weird "com455890" in the first error and the weird "comitempf" in the 2nd.

The queries are all simple ones of the format:

`rrset/name/<domainname>`

This is using:

```
$ dnsdbq -v
dnsdbq: version 2.6.4
```

Bug?

**Comment by stsauver** [comment]
Simpler example a colleague suggested:

```
$ dnsdbq -r 455890.com. -t TXT -j -s -k first
dnsdbq [2024-11-01 18:19:57]: warning: no seventh SP in '1618298208 1618786009 487801 9 com455890 TXT  {"obj":{"count":9,"time_first":1618298208,"time_last":1618786009,"rrname":"455890.com.","rrtype":"TXT","bailiwick":"455890.com.","rdata":[""]}}
```

**Comment by vixie** [comment]
bug! thanks joe. please try issue_231 branch before i request a pullup.

Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 16 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.09 KiB | 1.09 MiB/s, done.
Total 7 (delta 5), reused 0 (delta 0), pack-reused 0

**Comment by stsauver** [comment]
Looks good, TYVM!
