### ISSUE TITLE
DNSDB_SERVER change in expectation

### ISSUE THREAD

**Issue by bapril** [dnsdb/dnsdbq#26]
dnsdb_query(.py) is expecting:

DNSDB_SERVER="https://api.dnsdb.info"

dnsdbq appears to need the following to function:

DNSDB_SERVER="https://api.dnsdb.info/lookup"

The manpage states: 

"DNSDB_SERVER: contains the URL of the DNSDB API server (default is https://api.dnsdb.info)"

**Comment by djw1149** [comment]
That is the (incorrect) behavior on the branch master.  It is fixed in branch info.  I just created pull request https://github.com/dnsdb/dnsdbq/pull/27 to merge info into master.
