### ISSUE TITLE
No error message from a bad DNSDB_SERVER environment variable

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdbq#28]
If you run dnsdbq with a bad DNSDB_SERVER environment variable, it may silently exit, with status 0.  It should display an error message and fail with a non-zero status.
```
$ DNSDB_SERVER=https://api-pao.dnsdb.infoFOFOFO dnsdbq -i 128.89.0.1
$ echo $?
0
```

You need three -d flags to get to see an error message:

```
$ DNSDB_SERVER=https://api-pao.dnsdb.infoFOFOFO dnsdbq -i 128.89.0.1 -d -d -d
... 14 lines deleted ...
* Could not resolve host: api-pao.dnsdb.infoFOFOFO
* Closing connection 0
about to call exit(0)
```

**Comment by vixie** [comment]
there is no callback from libcurl to distinguish this outcome. it calls writerfunc, and the response code is 0. i believe it's a design error that curl_easy is synchronous and so a dns error in that case can be returned at the time of request initialization, whereas curl_multi is asynchronous and provides no way to learn whether something went wrong asynchronously before the connection was made. advice welcome.

**Comment by djw1149** [comment]
See branch report_async_curl_errs for a start at this.
Commit message:
    Print curl failure status returned from curl_multi_info_read, such as:
            libcurl failed since could not resolve the hostname
            libcurl failed since could not connect
    dnsdbq should exit with a non-zero status in case of curl failure, but that is not implemented (yet).

**Comment by vixie** [comment]
branch has been merged. leaving this issue open until we decide to add an exit(1) to the error outputs.

**Comment by vixie** [comment]
Pull #58.
