### ISSUE TITLE
if there's a /path after the host, don't add /lookup here

### ISSUE THREAD

**Issue by reedjc** [dnsdb/dnsdbq#42]
This hit me. Please document it. Or just always set to /lookup?

 /* if there's a /path after the host, don't add /lookup here. */
        x = 0;
        for (p = dnsdb_server; *p != '\0'; p++)
                x += (*p == '/');
        lookup = (x < 3) ? "/lookup" : "";

**Comment by vixie** [comment]
some dnsdb server prefixes have a path. so, the default path is /lookup, 
but won't be add any path at all if one was specified as part of the 
server spec.

**Comment by vixie** [comment]
Pull #57.
