### ISSUE TITLE
daylight savings time confusion with date string, off by 3600 seconds

### ISSUE THREAD

**Issue by reedjc** [dnsdb/dnsdbq#43]
I have 47 dnsdbq tests (out of my ~133 DNSDB API tests). I introduced a new test today which confused me. I tried to use -A for five minutes ago, but kept getting 404 on an active server. The dnsdbq output is clear about the problem but I also looked at code and added some debugging to confirm it.

mktime(3) used tm_isdst which made it one hour in the future (so per my query was 55 minutes in the future).  I see this on both Linux and NetBSD.

For example:
$ date -d "5 minutes ago" +"%Y-%m-%d %H:%M:%S"
2018-10-03 17:08:44

$ ./dnsdbq -A "2018-10-03 17:08:44" -r net/ANY

libcurl: 404 (https://api.dnsdb.info/lookup/rrset/name/net/ANY?time_last_after=1
538608124)
please note: 404 usually just means that no records matched the search criteria
API: Error: no results found for query.

So check out the epoch in the libcurl line above...
t1:dnsdbq$ date -r 1538608124
Wed Oct  3 18:08:44 CDT 2018

My goal was after 17:08 which would have worked:

t1:dnsdbq$ date
Wed Oct  3 17:15:33 CDT 2018

Using the epoch works and using the ns_parse_ttl() way works too, for example this works great:
dnsdbq -A "5m" -r net/ANY

By the way, I don't get any additional timezone adjustment on Linux or NetBSD (I am at CDT) so here.tz_minuteswest is 0. (I added debugging to confirm.)

I'd suggest:

 - documenting in the man page to say that DNSDB timestamps are in UTC timezone, but this tool uses local time which converts to UTC.

  - or document for the user to use UTC and don't adjust for that.

  - fix the off by 3600 seconds issue. My hack was to set 
tt.tm_isdst = 0;       /* don't adjust for daylight savings time */
before the mktime() use. I don't think that is the right way. Maybe mktime() is the wrong function to use for this. (Then tm_isdst gets reset to 1.) 

 - let's also document that the Unix epoch time is acceptable input (an example does show it)

 - and document the ns_parse_ttl() format which is the (weeks, days, hours, minutes, seconds) time before the current time.

**Comment by vixie** [comment]
reedjc wrote:
...
> I'd suggest:
...


>
>   *
>
>     or document for the user to use UTC and don't adjust for that.
>
>   *

this, please.

no security researcher should ever work or think in local time.

>   *
>
>     and document the ns_parse_ttl() format which is the (weeks, days,
>     hours, minutes, seconds) time before the current time.

this, also.

-- 
P Vixie

**Comment by djw1149** [comment]
Fixed in commit cfa5ce7
