### ISSUE TITLE
document that HTTPS proxies are supported

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdbq#53]
dnsdbq's use of libcurl means that it supports the environment variable and HTTPS_PROXY.  Document that support

**Comment by vixie** [comment]
"This is more a convention than a standard." (https://superuser.com/questions/944958/are-http-proxy-https-proxy-and-no-proxy-environment-variables-standard). the documentation for this is at best inconsistent. until libcurl documents it better than today, and until we either commit to using libcurl for all time or commit to supporting libcurl's style of proxy settings for all time, we should not document this side effect of our present use of libcurl.
