### ISSUE TITLE
should batch mode calculate a new "now" time for each line of input?

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdbq#74]
in batch mode (-f), the time for relative time ranges is calculated once, based upon the time dnsdbq starts. If batch mode runs for a long time, that time will become stale.
Example, when running "dnsdbq -f -A30d -klast -S -L1 -j" the time_last_after value is set at start-time, and never changes for the running life of the process.

The alternative would be to calculate the relative time for each line of batch mode input.  Perhaps have this be a command-line option.  
This behavior can be achieved with the existing code by not using batch mode, or using batch mode with a small list of inputs, submitted in a short time interval, and then exiting and restarting dnsdbq for the next time slot.

The recommended  fix is simply documenting the existing behavior.

**Comment by vixie** [comment]
documenting it sounds right. adding an option may be a reluctant eventual necessity

**Comment by djw1149** [comment]
https://github.com/dnsdb/dnsdbq/pull/75 documents it.
