### ISSUE TITLE
.. and . squashing (losing dot)

### ISSUE THREAD

**Issue by reedjc** [dnsdb/dnsdbq#78]
Looking at server logs, I see .. and . are squashed. Even .. makes it so previous parameter in URL is removed (like name/.. or ANY/.. disappears). (I have no need for .. but it shows the problem.) My problem was seen trying to use find bailiwick of . (-b .) was not sent to the DNSDB API server.

It appears that the problem began in libcurl version 7.32.0 which introduced Curl_dedotdotify().
dnsdbq requires curl_multi_wait introduced in curl 7.28.0 which works fine for . and .. by not removing them.
libcurl 7.42.0 introduces CURLOPT_PATH_AS_IS option.
So for 7.42.0 and newer this worked for me:
+++ b/dnsdbq.c
@@ -1412,6 +1412,8 @@ launch_one(writer_t writer, char *url) {
        curl_easy_setopt(reader->easy, CURLOPT_HTTPHEADER, reader->hdrs);
        curl_easy_setopt(reader->easy, CURLOPT_WRITEFUNCTION, writer_func);
        curl_easy_setopt(reader->easy, CURLOPT_WRITEDATA, reader);
+        /* don't squash "/../" or "/./" especially for dot */
+       curl_easy_setopt(reader->easy, CURLOPT_PATH_AS_IS, 1L);

(The logging also showed the literal .. and .)
Should check for CURLOPT_PATH_AS_IS defined and use it? Require at least that version?
(Create a new metadomain ___DNSDB_DOTDOT___ and ___DNSDB_DOT___ for example that is used by the client and known by the DNSDB API server? It could be used by other internal client that also loses dot.)

**Comment by djw1149** [comment]
fixed in PR#91
