### ISSUE TITLE
don't allow -S or -s with -I

### ISSUE THREAD

**Issue by reedjc** [dnsdb/dnsdbq#82]
dnsdbq -I allows -s and -S switches but makes no sense

(I'd ignore this but code already has many command-line switches checks.)

**Comment by vixie** [comment]
it's legit.

`vixie@linux-9daj:~/src/gh/dnsdbq> ./dnsdbq -l 3 -r vix.su/ns -j | jq .time_first
1283180432
1459058242
1332392231
vixie@linux-9daj:~/src/gh/dnsdbq> ./dnsdbq -l 3 -r vix.su/ns -j -s | jq .time_first
1283180432
1332392231
1459058242`

however, the documentation can be improved.
