### ISSUE TITLE
several -J command-line switches checks and documentation

### ISSUE THREAD

**Issue by reedjc** [dnsdb/dnsdbq#85]
Since dnsdbq already fails on some wrong command-line option combinations, consider some more for -J:

1) dnsdbq allows -t with -J mode, but -t is ignored
fail if -t is also set

2) dnsdbq allows -V summarize with -J mode, but -V summarize is ignored
        (also -M is allowed with -J)
fail if -V is also set

3) please better document dnsdbq -J mode. It can be sorted for example.
It can be limitted with -l and -L  and -A and -B (that is surprising to me). what else?

4) Does allowing -J with -g make sense?  it cannot change aggregation

5) dnsdbq -O is allowed with -J and -O does nothing.

6) dnsdbq -J shouldn't allow -u since does nothing

**Comment by vixie** [comment]
all fixed.
